/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.LogicaUsbModem;
import Modelo.UsbModem;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author stefania
 */
public class ModificarModem extends javax.swing.JFrame {

    LogicaUsbModem lum = new LogicaUsbModem();
    
    public ModificarModem(Long cod) {
        initComponents();
        this.setTitle("Modificar Modem");
        this.setResizable(false);
        this.setLocationRelativeTo(null); 
        llenarCampos(cod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        activoModem = new javax.swing.JRadioButton();
        inactivoModem = new javax.swing.JRadioButton();
        ProveedorModem = new javax.swing.JComboBox<>();
        NombreModem = new javax.swing.JTextField();
        DisponibilidadModem = new javax.swing.JComboBox<>();
        GuardarModem = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        CostoModem = new javax.swing.JFormattedTextField();
        PrecioModem = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        CodigoModem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Modem");

        jLabel2.setText("Nombre Modem:");

        jLabel3.setText("Proveedor:");

        jLabel4.setText("Disponibilidad:");

        jLabel5.setText("Costo por día:");

        jLabel6.setText("Precio por día:");

        jLabel7.setText("Estado:");

        buttonGroup1.add(activoModem);
        activoModem.setText("Activo");

        buttonGroup1.add(inactivoModem);
        inactivoModem.setText("Inactivo");

        ProveedorModem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Claro", "Movistar", "Tigo", "Uff", "Virgin" }));

        DisponibilidadModem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Alquilado", "Reservado", "Alquilado-Reservado" }));

        GuardarModem.setText("Guardar");
        GuardarModem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarModemActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        CostoModem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        PrecioModem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel8.setText("Código Modem:");

        CodigoModem.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(GuardarModem)
                        .addGap(49, 49, 49)
                        .addComponent(Cancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGap(8, 8, 8)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodigoModem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(activoModem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inactivoModem))
                                .addComponent(ProveedorModem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DisponibilidadModem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CostoModem)
                                .addComponent(PrecioModem)
                                .addComponent(NombreModem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoModem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreModem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ProveedorModem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DisponibilidadModem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostoModem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioModem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activoModem)
                    .addComponent(inactivoModem)
                    .addComponent(jLabel7))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarModem)
                    .addComponent(Cancelar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Método que guarda el modem modificado al presionar el botón. Busca en la BD
       el modem seleccionado en la tabla, imprime los datos en la ventana y guarda
       nuevamente el objeto de tipo UsbModem en la base de datos.
       Entrada: evento del botón
       Salida: ---    
    */
    private void GuardarModemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarModemActionPerformed
        long cod = Long.parseLong(CodigoModem.getText());
        UsbModem um = null;
        try {
            um = lum.consultarModemCodigo(cod);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
        if(NombreModem.getText().equals("")){
            JOptionPane.showMessageDialog(null, "El nombre es obligatorio");
        }else{
            um.setNombremodem(NombreModem.getText());
            
            um.setProveedor(ProveedorModem.getSelectedItem().toString());
            um.setDisponibilidad(DisponibilidadModem.getSelectedItem().toString());

            if(CostoModem.getText().equals("")){
                um.setCostodia(0);
            }else{
                um.setCostodia(Integer.parseInt(CostoModem.getText()));
            }

            if(PrecioModem.getText().equals("")){
                um.setPreciodia(0);
            }else{
                um.setPreciodia(Integer.parseInt(PrecioModem.getText()));
            }


            if(activoModem.isSelected()){
                um.setEstadousbmodem(true);
            }else if(inactivoModem.isSelected()){
                um.setEstadousbmodem(false);
            }else{
                JOptionPane.showMessageDialog(null, "Por favor seleccione un estado");
            }

            lum.modificarModem(um);
            
            dispose();          
        }
    }//GEN-LAST:event_GuardarModemActionPerformed

    /* Método para cerrar la ventana y descartar cualquier cambio
       al presionar el botón
       Entrada: evento del botón
       Salida: ---
    */
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    /* Método para mostrar los datos del modem seleccionado en la ventana de
       modificación. Realiza una consulta en la BD con el código del objeto.
       Entrada: código de tipo Long del usbmodem
       Salida: ---
    
    */
    private void llenarCampos(Long cod){
        UsbModem um = null;
        try {
            um = lum.consultarModemCodigo(cod);
            
            CodigoModem.setText(um.getCodigomodem()+"");
        
            NombreModem.setText(um.getNombremodem());

            for (int i = 0; i < ProveedorModem.getItemCount(); i++) {
                if(ProveedorModem.getItemAt(i).equals(um.getProveedor())){
                    ProveedorModem.setSelectedIndex(i);
                }
            }

            for (int i = 0; i < DisponibilidadModem.getItemCount(); i++) {
                if(DisponibilidadModem.getItemAt(i).toString().equals(um.getDisponibilidad())){
                    DisponibilidadModem.setSelectedIndex(i);
                }
            }

            CostoModem.setText(um.getCostodia()+"");
            PrecioModem.setText(um.getPreciodia()+"");

            if(um.getEstadousbmodem()){
                activoModem.setSelected(true);
            }else{
                inactivoModem.setSelected(true);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
        
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField CodigoModem;
    private javax.swing.JFormattedTextField CostoModem;
    private javax.swing.JComboBox<String> DisponibilidadModem;
    private javax.swing.JButton GuardarModem;
    private javax.swing.JTextField NombreModem;
    private javax.swing.JFormattedTextField PrecioModem;
    private javax.swing.JComboBox<String> ProveedorModem;
    private javax.swing.JRadioButton activoModem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton inactivoModem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
